language: csharp
mono: none
dotnet: 2.1.4
install:
  - dotnet restore
script:
  - dotnet build ./src/CodeWarsKata.ClassLib/
  - dotnet build ./src/CodeWarsKata.ConsoleApp/
  # - dotnet run --project ./src/CodeWarsKata.ConsoleApp/CodeWarsKata.ConsoleApp.csproj
